export const HealthCondition = Object.freeze({
    Obesity: "Obesity",
    Diabetes: "Diabetes",
    Hypertension: "Hypertension",
    Hyperlipidemia: "Hyperlipidemia",
    Metabolic_Syndrome: "Metabolic_Syndrome",
    Lactose_Intolerance: "Lactose_Intolerance",
    IBS: "IBS",
    Gluten_Sensitivity: "Gluten_Sensitivity",
    GERD: "GERD",
    PCOS: "PCOS",
    Pregnancy: "Pregnancy",
    Lactation: "Lactation",
    Menopause: "Menopause",
    Anemia: "Anemia",
    Muscle_Gain: "Muscle_Gain",
    Body_Recomposition: "Body_Recomposition",
    Endurance: "Endurance",
    Sarcopenia: "Sarcopenia",
    Gout: "Gout",
    NAFLD: "NAFLD",
    CKD_Early: "CKD_Early",
    Osteoporosis: "Osteoporosis",
    Inflammation: "Inflammation",
    Vegan: "Vegan",
    Keto: "Keto",
    Mediterranean: "Mediterranean",
    Intermittent_Fasting: "Intermittent_Fasting",
});

export const healthConditionMap = {
    "Weight Loss / Obesity": HealthCondition.Obesity,
    "Diabetes (High Blood Sugar)": HealthCondition.Diabetes,
    "High Blood Pressure": HealthCondition.Hypertension,
    "High Cholesterol": HealthCondition.Hyperlipidemia,
    "Metabolic Issues": HealthCondition.Metabolic_Syndrome,
    "Lactose Intolerance": HealthCondition.Lactose_Intolerance,
    "Irritable Bowel Syndrome (IBS)": HealthCondition.IBS,
    "Gluten Sensitivity": HealthCondition.Gluten_Sensitivity,
    "Acidity / Acid Reflux (GERD)": HealthCondition.GERD,
    "PCOS (Hormone Imbalance)": HealthCondition.PCOS,
    Pregnancy: HealthCondition.Pregnancy,
    Breastfeeding: HealthCondition.Lactation,
    Menopause: HealthCondition.Menopause,
    "Low Iron (Anemia)": HealthCondition.Anemia,
    "Muscle Gain": HealthCondition.Muscle_Gain,
    "Fat Loss + Muscle Gain": HealthCondition.Body_Recomposition,
    "Endurance Training": HealthCondition.Endurance,
    "Age-related Muscle Loss": HealthCondition.Sarcopenia,
    "High Uric Acid (Gout)": HealthCondition.Gout,
    "Fatty Liver": HealthCondition.NAFLD,
    "Early Kidney Disease": HealthCondition.CKD_Early,
    "Weak Bones": HealthCondition.Osteoporosis,
    "Chronic Inflammation": HealthCondition.Inflammation,
    "Vegan Diet": HealthCondition.Vegan,
    "Keto Diet": HealthCondition.Keto,
    "Mediterranean Diet": HealthCondition.Mediterranean,
    "Intermittent Fasting": HealthCondition.Intermittent_Fasting,
};
