export const healthConditionOptions = [
  { value: "Obesity", label: "Obesity" },
  { value: "Diabetes", label: "Diabetes" },
  { value: "Hypertension", label: "Hypertension (High Blood Pressure)" },
  { value: "Hyperlipidemia", label: "Hyperlipidemia (High Cholesterol)" },
  { value: "Metabolic_Syndrome", label: "Metabolic Syndrome" },
  { value: "Lactose_Intolerance", label: "Lactose Intolerance" },
  { value: "IBS", label: "Irritable Bowel Syndrome (IBS)" },
  { value: "Gluten_Sensitivity", label: "Gluten Sensitivity" },
  { value: "GERD", label: "GERD (Acid Reflux)" },
  { value: "PCOS", label: "PCOS (Polycystic Ovary Syndrome)" },
  { value: "Pregnancy", label: "Pregnancy" },
  { value: "Lactation", label: "Lactation (Breastfeeding)" },
  { value: "Menopause", label: "Menopause" },
  { value: "Anemia", label: "Anemia" },
  { value: "Muscle_Gain", label: "Muscle Gain" },
  { value: "Body_Recomposition", label: "Body Recomposition (Fat Loss + Muscle Gain)" },
  { value: "Endurance", label: "Endurance Training" },
  { value: "Sarcopenia", label: "Sarcopenia (Age-related Muscle Loss)" },
  { value: "Gout", label: "Gout (High Uric Acid)" },
  { value: "NAFLD", label: "NAFLD (Fatty Liver Disease)" },
  { value: "CKD_Early", label: "Chronic Kidney Disease (Early Stage)" },
  { value: "Osteoporosis", label: "Osteoporosis (Bone Weakness)" },
  { value: "Inflammation", label: "Chronic Inflammation" },
  { value: "Vegan", label: "Vegan Diet" },
  { value: "Keto", label: "Ketogenic Diet (Keto)" },
  { value: "Mediterranean", label: "Mediterranean Diet" },
  { value: "Intermittent_Fasting", label: "Intermittent Fasting" },
];
